# Generated by Django 5.1.4 on 2025-01-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EkVayu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='UserOs',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
