# Generated by Django 5.1.4 on 2025-01-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EkVayu', '0002_details_useros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='UserOs',
            new_name='useros',
        ),
    ]
