# Generated by Django 5.1.4 on 2025-01-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EkVayu', '0003_rename_useros_details_useros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='useros',
        ),
        migrations.AddField(
            model_name='details',
            name='UserOS',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
