# Generated by Django 5.1.4 on 2025-01-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EkVayu', '0004_remove_details_useros_details_useros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
