# Generated by Django 5.1.4 on 2025-01-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EkVayu', '0006_rename_useros_details_os_remove_details_uniqueid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='unique_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
