# Generated by Django 5.1.4 on 2025-01-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EkVayu', '0007_alter_details_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ekvayu_visit_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Total Visits',
            },
        ),
        migrations.AlterModelOptions(
            name='details',
            options={'verbose_name_plural': 'Details'},
        ),
        migrations.RenameField(
            model_name='details',
            old_name='Timezone',
            new_name='timezone',
        ),
    ]
