# Generated by Django 5.1.4 on 2025-01-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EkVayu', '0008_totalvisits_alter_details_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='unique_id',
            new_name='uniqueId',
        ),
    ]
