# Generated by Django 5.1.4 on 2025-01-14 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EkVayu', '0009_rename_unique_id_details_uniqueid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='ekvayu_visit_count',
        ),
    ]
