# Generated by Django 5.1.4 on 2025-01-15 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EkVayu', '0013_alter_offers_description_alter_offers_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('features', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer_type', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Offers',
        ),
    ]
